---
title: 'Before we start'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- Where can I meet other workshop participants?
- Where can I fill in my questions about the workshop topic?
- Where can I find the Code of Conduct?
- How can I report unacceptable behaviour?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Share our communication forum.
- Share our Code of Conduct.

::::::::::::::::::::::::::::::::::::::::::::::::

## Roll call

:::checklist

Hello!

Before we start, tell us something about you on our _communication forum_ called [GitHub Discussions](https://github.com/epiverse-trace/research-compendium/discussions/1).

<!-- You can fill in your questions on the topic under the [Q&A category](https://github.com/epiverse-trace/research-compendium/discussions/categories/q-a). -->

:::

## Welcome

:::checklist

A reminder of our [Code of conduct](https://github.com/epiverse-trace/.github/blob/main/CODE_OF_CONDUCT.md):

- If you experience or witness unacceptable behaviour or have any other concerns, please report by completing this short form:  <https://forms.gle/guKqVXPk6K43jPn59>

- To report an issue involving one of the organisers, please use the LSHTM’s [Report and Support tool](https://reportandsupport.lshtm.ac.uk/), where your concern will be triaged by a member of LSHTM’s Equity and Diversity Team.

:::


::::::::::::::::::::::::::::::::::::: keypoints 

- Use the `GitHub Discussions` as our communication forum for the workshop.
- Use the Code of Conduct to report unacceptable behaviour.

::::::::::::::::::::::::::::::::::::::::::::::::

